version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091
  mysql:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: defPassword
      MYSQL_USER: defUser
      MYSQL_PASSWORD: defPassword
      MYSQL_DATABASE: keymanager
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
